### ISSUE TITLE
Hero text word-breaks on mobile devices

### ISSUE THREAD

**Issue by wfowler9** [godaddy-wordpress/primer-child-uptownstyle#27] opened 2017-03-29 05:20 UTC
Hero text should resize and not break within words.

![aaa_site copy](https://cloud.githubusercontent.com/assets/26758395/24439684/81d8801e-149b-11e7-85bc-a413ca95c6b2.jpg)

![aaa_mobile](https://cloud.githubusercontent.com/assets/26758395/24439705/9701b096-149b-11e7-8c77-d52ba15588e1.jpg)

**Comment by EvanHerman** [comment] 2017-03-29 12:57
Hi @wfowler9,

Thanks for reporting the bug here. I was able to reproduce things on my end as well. I will be looking into this issue and patching it up in the next release, which we are currently working on getting ready to ship.

**Comment by wfowler9** [comment] 2017-04-13 23:44
There appears to have been an update to the theme, however, the bug still remains (NOTE: it only occurs on phones when held in a portrait orientation). Am I jumping the gun?

**Comment by divyanshpuri02** [comment] 2017-04-22 16:04
See the only solution to this problem is just make the h1 heading font style different from what it is and there will be another option there just untick it

**Comment by EvanHerman** [comment] 2017-04-27 21:02
Hi @wfowler9,

No I believe this is still an issue. We have a proposed solution (see here https://github.com/godaddy/wp-primer-theme/issues/177) but it's something we need to revisit and decide if that is the approach we want to take. Since the text lengths vary between site adjusting the font-size isn't going to be enough.

**Comment by wfowler9** [comment] 2017-04-27 22:35
Yes, it's still an issue. Changing fonts has no effect. What is interesting
is that words break in the same place regardless of the font. I had
expected that changes in the kerning pairs might have altered this, but it
appears it doesn't.

**Comment by amandallogan** [comment] 2018-07-18 17:31
I noticed that there has been yet another theme update but the word breaks in the hero text still appear to be an issue on mobile. Is there ETA for when we can expect a solution for this?

**Comment by mattdevo1** [comment] 2018-09-21 21:33
Are there any plans to fix this bug? Looks like it's still an open issue.

**Comment by wfowler9** [comment] 2018-09-22 14:58
...and I would really like it fixed, if possible.

**Comment by aledesma-godaddy** [comment] 2023-03-13 17:30
Closing issues and PRs in preparation for repository archival

**Closed by aledesma-godaddy** 2023-03-13 17:30 UTC
Labels: bug
